apiVersion: v1
data:
  allrockologsdashboard.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "grafana",
              "uid": "-- Grafana --"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 13,
      "links": [],
      "panels": [
        {
          "datasource": {
            "type": "loki",
            "name": "loki"
          },
          "gridPos": {
            "h": 20,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "options": {
            "dedupStrategy": "none",
            "enableLogDetails": true,
            "prettifyLogMessage": false,
            "showCommonLabels": false,
            "showLabels": false,
            "showTime": false,
            "sortOrder": "Descending",
            "wrapLogMessage": false
          },
          "targets": [
            {
              "datasource": {
                "type": "loki",
                "name": "loki"
              },
              "editorMode": "code",
              "expr": "{kubernetes_namespace_name=~\"rocko.*\"} |= ``",
              "queryType": "range",
              "refId": "A"
            }
          ],
          "title": "All logs from NS with Rocko in the Name",
          "type": "logs"
        }
      ],
      "schemaVersion": 39,
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-1h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "browser",
      "title": "All Rocko NS Logs",
      "uid": "fe6xbq3xleyo0b",
      "version": 3,
      "weekStart": ""
    }
kind: ConfigMap
metadata:
  name: allrockologsdb
  namespace: rocko-grafana
