apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
  namespace: openshift-logging
stringData:
  access_key_id: hitnvOI8gRZDBPHmL403
  access_key_secret: Re1XWsEOmG2ufpFof0FK7QUUj2mHGHX7U1BI98Wk
  bucketnames: loki
  endpoint: http://minio.minio.svc:9000
