apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mino
  namespace: minio
spec:
  port:
    targetPort: minio-console
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: minio
    weight: 100
  wildcardPolicy: None
